fix: add fallback to get the dist key
Signed-off-by: Arjun Kesava P <arjun.kesava@gmail.com>

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -340,6 +340,14 @@ jobs:
         with:
           path: '**/dist'
           key: dist-${{ env.rid }}
+          restore-keys: |
+            dist-
+
+      - name: Debug dist
+        run: |
+          pkg_name=${{ matrix.package }}
+          ls -R packages/$(basename $pkg_name)/dist || echo "Dist is missing!"
+
 
       - name: Synchronize Packages
         run: yarn
