fix: add fallback to get the dist key and fix github actions cache (#1363)
* fix: add fallback to get the dist key

Signed-off-by: Arjun Kesava P <arjun.kesava@gmail.com>

* chore: rm restore-keys pattern from pull request yaml

Signed-off-by: Arjun Kesava P <arjun.kesava@gmail.com>

---------

Signed-off-by: Arjun Kesava P <arjun.kesava@gmail.com>

diff --git a/.github/workflows/pull-request.yml b/.github/workflows/pull-request.yml
--- a/.github/workflows/pull-request.yml
+++ b/.github/workflows/pull-request.yml
@@ -341,6 +341,12 @@ jobs:
           path: '**/dist'
           key: dist-${{ env.rid }}
 
+      - name: Debug dist
+        run: |
+          pkg_name=${{ matrix.package }}
+          ls -R packages/$(basename $pkg_name)/dist || echo "Dist is missing!"
+
+
       - name: Synchronize Packages
         run: yarn
 
